name = "fairyrealm-worker"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[vars]
# Environment variables

[[d1_databases]]
binding = "DB"
database_name = "fairyrealm-db"
database_id = "dba1f550-621b-4a16-9557-cb5856426051"
preview_database_id = "dba1f550-621b-4a16-9557-cb5856426051" # Optional

[ai]
binding = "AI"
